### ISSUE TITLE
Error: Match error: Failed Match.OneOf or Match.Optional validation

### ISSUE THREAD

**Issue by adnanbrq** [percolatestudio/momentum-iron-router#12]
Hello people,

I'm trying to implement this plugin but I can't get it to work as it should.
It prints the following in the console:
"Exception from Tracker afterFlush function:
debug.js:41 Error: Match error: Failed Match.OneOf or Match.Optional validation
    at checkSubtree (match.js:244)
    at check (match.js:32)
    at momentum-iron-router.js:25
    at Template.momentum.rendered (momentum.js:10)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:205)
    at view.js:104
    at Object.Blaze._withCurrentView (view.js:523)"

I'm using the meteor-boilerplate from matteodem.
My router.js file looks like this: ( Location: routes )

Router.map(function() {
    this.route('/', {
        name: 'home',
        action: function () {
            this.render('home');
            SEO.set({ title: 'Home - ' + Meteor.App.NAME });
        }
    }),
    this.route('/lol', {
        name: 'lol',
        action: function () {
            this.render('lol');
            SEO.set({ title: 'Lol - ' + Meteor.App.NAME });
        }
    })
})

My Layout Template ( the layout ) ( Location: client/views/layout )
<template name="basicLayout">
    <div id="main">
        {{#momentum plugin='iron-router' options=transition}}
            {{> yield}}
        {{/momentum}}
    </div>
</template>

Template for /test and test.js ( Location: client/views/test )
<template name="test">
    <div class="container-fluid" style="background-color: yellow;">
        TEST PAGE 
    </div>
</template>

Template.test.transition = function() {
    return function(from, to, element) {
        return 'right-to-left';
    }
}

I hope someone can help me

**Comment by sangyoo91** [comment]
getting same error.

**Comment by boogieprod** [comment]
Hey guys, I had the same error (forgot to add coffeescript package in my project even though I wrote the momentum script in coffee). Let me know if that helped, if not please send a reproduction app:  https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor.

Code snippets are hard to debug :).

Thanks,

**Comment by evolross** [comment]
+1. Same error.  Added coffeescript.  Still have the error.

**Comment by boogieprod** [comment]
@evolross can you reproduce a simple app showing the issue so I can help you out. If you're not familiar with repos follow this guide.

https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

Thanks,
