### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [percolatestudio/momentum-iron-router#14]
I tried using it and it did not work for me.

**Comment by Laurentiu-Andronache** [comment]
My setup is very simple. In master_layout.html I have a header followed by:

```
  {{#momentum plugin='iron-router' options=transition}}
    {{> yield}}
  {{/momentum}}
```

and in master_layout.js I have

```
Template.MasterLayout.helpers({
  'isActiveRoute': routeName => Router.current().route.getName() === routeName ? 'active' : ''
  ,
  transition: () => (from, to, element) => to.template === "bets" ? 'left-to-right' :  'right-to-left'
});
```

**Comment by Laurentiu-Andronache** [comment]
Hmmm... I found that I was getting this in the Console, even though I had check@1.1.0 in the .meteor/versions file:

```
Exception from Tracker afterFlush function:
debug.js:41 ReferenceError: check is not defined
    at percolate_momentum-iron-router.js:33
    at Template.momentum.rendered (percolate_momentum.js:48)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:457)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:205)
    at view.js:107
    at Object.Blaze._withCurrentView (view.js:538)
    at view.js:106
    at Object.Tracker._runFlush (tracker.js:497)
```

I used meteor add check and now the transitions work.

New issue though... why do the templates that are yielded come from the sides but also from below and jump above in the normal position after the transition is done? The transitions are not only from right to left or from left to right. They're more like:
1. start from wrong position in the lower right instead of just right
2. transition to the center
2. jump up in the correct position

**Comment by Laurentiu-Andronache** [comment]
Using position: absolute; in my yields has removed the jump up post-effect but now they stay in top left. How do I center them in the middle of the page? I also have bootstrap...

**Comment by Laurentiu-Andronache** [comment]
If I use an absolute positioning, it ruins the page at lower resolutions. Mate I think you should remove this plugin from Atmosphere, otherwise you'll just waste the time of a lot of people...

**Comment by Laurentiu-Andronache** [comment]
Another bug is that dropdowns from inside the wrapped div have a messed up z-index. When you expand them, they appear behind other elements in the page.

**Comment by ryanhanwu** [comment]
the `check` is from Meteor, try `meteor add check`

**Comment by domyen** [comment]
The plugin still works. 

Momentum's basic behavior is to wrap incoming/outgoing nodes in a DOM element. In order for animations that involve absolute positioning to work, you need to style the momentum wrapper. This can sometimes mean style tweaks to your UI library.
