### ISSUE TITLE
Use question

### ISSUE THREAD

**Issue by zleman1593** [percolatestudio/momentum-iron-router#3]
I am using the template:

```
<template name="layout">
  <div class="container">
    {{>header}}
    {{> errors}}
    <div id="main" class="row-fluid">
{{#momentum with='iron-router' options=transitionOptions}}
      {{> yield}}
{{/momentum}}
    </div>
  </div>
</template>
```

Is the following correct?
```
Template.layout.transitionOptions = function(from, to, element) {
  return 'right-to-left';
};
```

I am not seeing any transitions when switching pages using this. Am I using the transitionOptions incorrectly?
Any tips would be appreciated, as there isn't much documentation. Thanks.

**Comment by Pushplaybang** [comment]
same error here. exactly as above.

**Comment by jgladch** [comment]
same here

**Comment by zol** [comment]
Could someone post a repro please.

**Comment by jgladch** [comment]
Alrighty, in trying to set you up with a repro, I've managed to find my issue (go figure :P )

This setup is now working for me:

### In layout template:
<pre><code>{{#momentum plugin='iron-router' options=transition}}
   {{> yield}}
{{/momentum}}
</code></pre>

### In layout.js:
<pre><code>Template.layout.helpers({
  transition : function(){
    return function(){
      return 'right-to-left';
    }
  }
});
</code></pre>

**Comment by zol** [comment]
Great!

**Comment by funkyeah** [comment]
I stumbled on this for a bit and I think the most likely culprit is the use case assumptions people are making.

A lot of people have something along the lines of a layout template:

     <template name="layout">
         {{#momentum plugin='iron-router' options=transition}}
             {{> yield}}
         {{/momentum}}
     </template>

and then may very well be calling 
`Templat.X.transition`

or

    Template.x.helpers
        transition: ->
            (from, to, element) ->
                    return 'right-to-left'

on the individual template they are expecting to transition. This won't work and in this use case example you can only call `Template.layout.transition` or helpers equivalent. For me getting the current route `Router.current().route.getName()` and returning the appropriate transition for that route worked

**Comment by jgladch** [comment]
Yes, that's exactly what had happened in my case.
