### ISSUE TITLE
recommendations for keeping pages side by side when animating?

### ISSUE THREAD

**Issue by funkyeah** [percolatestudio/momentum-iron-router#9]
When I use the left-to-right or right-to-left transition the second page always transitions in underneath the first as shown in the screenshot below. Any recommendations on how to fix this?

![screenshot from 2015-01-31 18 05 52](https://cloud.githubusercontent.com/assets/469403/5990383/dfbe680a-a973-11e4-8605-0de0de338f78.png)

Played with using absolute positioning and floating but I don't see how either could work. Both end up screwing up the animation quite a bit.

**Comment by funkyeah** [comment]
also, the rendered data disappears from the initial template when animating. bonus points for hints on that or if that is the only possible behavior

**Comment by zol** [comment]
You'll probably want to use scrollable divs with absolute positioning.

**Comment by funkyeah** [comment]
Seems reasonable if starting with the use of this package in-mind from the beginning. Any thoughts on how the package itself could solve this for the more general case? Maybe by apply positioning css to the injected divs when transitioning? From a bootstrap perspective it seems like this could almost work by applying:

````
.velocity-animating {
  position: absolute;
  left: 0px;
  right: 0px;
}
````
and then calculating the offset via `$("animated-div-selector").offset().top`

I don't have much experience in this area though to know how well this would work in the general case.

**Comment by zol** [comment]
@funkyeah momentum isn't intended to be a general solution. In our experience it is not possible to achieve a good result without using absolutely positioned scrollable divs. We won't be actively pursuing an alternate solution however, if someone from the community like yourself figures it out we'll be glad to take a look and integrate it if it works well.

**Comment by funkyeah** [comment]
Hey thanks for the feedback! The solution I outlined above has been working fairly well for me after some tweaking. 

I've already submitted a pull request for documentation updated unrelated to this particular issue. If that gets pulled in I'll probably add some more information about the discussion here as well to prevent another issue submission from someone else. Feel free to close whenever.
